# Copyright 2018, Juniper Networks Pvt Ltd.
# All rights reserved.
# command example: ansible-playbook -i all.inv 02-deploy-networks.yml
---
- name: install contrail
  hosts: contrail-ubuntu-vm
  gather_facts: false
  vars:
    openrc:
      OS_PROJECT_DOMAIN_NAME: default
      OS_USER_DOMAIN_NAME: default
      OS_PROJECT_NAME: admin
      OS_TENANT_NAME: admin
      OS_USERNAME: admin
      OS_PASSWORD: contrail123
      OS_AUTH_URL: http://10.10.7.149:35357/v3
      OS_INTERFACE: internal
      OS_IDENTITY_API_VERSION: 3

  environment: "{{ openrc }}"
  tasks:

    - name: Set necessary variables
      set_fact:
        os_auth:
          OS_AUTH_URL: http://10.10.7.205:35357/v3
          OS_USERNAME: admin
          OS_PASSWORD: contrail123
          OS_PROJECT_NAME: admin
          OS_TENANT_NAME: admin
          OS_PROJECT_DOMAIN_NAME: default
          OS_USER_DOMAIN_NAME: default
          OS_IDENTITY_API_VERSION=3
          OS_INTERFACE=internal

    - name: install shade 
      pip:
        name: shade

    - name: Add heat_stack_owner role
      os_user_role:
        user: admin
        role: heat_stack_owner
        project: admin

    - name: Install networks, subnet, and policy
      os_stack:
        name: deploy-networks
        state: present
        template: "/root/deploy-networks.yaml"

    - name: Sleep five seconds
      wait_for:
        timeout:5
 
    - name: Gather facts about previously created networks
      shell: openstack --os-auth-url "http://10.10.7.205:35357/v3" --os-username admin --os-project-name admin --os-tenant-name admin --os-password "contrail123" --os-default-domain-name default network list -f json
      register: network_list

    - name: Display Networks
      set_fact:
        networks: "{{ network_list.stdout | from_json | json_query(jq)}}"
      vars:
        jq: "[?contains(Name,'_network')].{Name:Name,ID:ID,Subnets:Subnets}"
    - debug:
        msg:
          - "{{networks}}"


    - name: Gather facts about previously created subnets
      shell: openstack --os-auth-url "http://10.10.7.205:35357/v3" --os-username admin --os-project-name admin --os-tenant-name admin --os-password "contrail123" --os-default-domain-name default subnet list -f json
      register: network_list

    - name: Display Networks
      set_fact:
        subnets: "{{ network_list.stdout | from_json | json_query(jq)}}"
      vars:
        jq: "[?contains(Name,'_subnet')].{ID:ID,Name:Name,Network:Network,Subnet:Subnet}"
    - debug:
        msg:
          - "{{subnets}}"

